name: Z2P Things You Can See
type: flutter # This should be either "dart" or "flutter".
steps:
  - name: Exercise 1
    directory: excercise1
    has_solution: true
  - name: Exercise 2
    directory: excercise2
    has_solution: true
